export { default as TopNav } from './TopNav'
export { default as Welcome } from './Welcome'
export { default as Nav } from './Nav'
export { default as About } from './About'
export { default as Contact } from './Contact'
export { default as Footer } from './Footer'